# Generated by Django 2.2.1 on 2019-10-26 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_auto_20191024_2006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diseases',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='diseases',
            name='weight',
        ),
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(default='', max_length=23),
        ),
        migrations.AddField(
            model_name='patient',
            name='weight',
            field=models.CharField(default='', max_length=6),
        ),
    ]
